# Generated by Django 2.2.1 on 2019-05-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biaoti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=30, verbose_name='string')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('pool', models.IntegerField(max_length=10, verbose_name='pool')),
                ('string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tou1.biaoti')),
            ],
        ),
    ]
